apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
#    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: nautilus.io/linstor
#                operator: In
#                values:
#                - "true"
      containers:
        - name: postgres
          image: postgres:latest
          resources:
            requests:
              cpu: "10"
              memory: "16Gi"
            limits:
              cpu: "20"
              memory: "32Gi"
          env:
            - name: POSTGRES_USER
              value: cinescope
            - name: POSTGRES_PASSWORD
              value: cine$c0pe
            - name: POSTGRES_DB
              value: cinescope
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
        - name: data-ingestion
          image: postgres:latest
          resources:
            requests:
              cpu: "4"
              memory: "1Gi"
            limits:
              cpu: "8"
              memory: "4Gi"
          command: ["/bin/sh", "-c", "apt-get update && apt-get install vim python3 python3-venv python3-pip -y && sleep infinity"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: distributed-data
            #claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
