---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: flask-svc
  name: flask-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: flask-http
  type: ClusterIP
