apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: flask-http
  template:
    metadata:
      labels:
        k8s-app: flask-http
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
      containers:
        - name: flask
          image: joelpolizzi/flask-dsc202:latest
          command: ["/bin/sh", "-c"]
          args: 
            - apt-get update && 
              apt-get install procps -y &&
              pip install psycopg2-binary pandas openai redis neo4j && 
              cd /jupyter-data/cinescope/jupyter-code/ && sh watchdog.sh
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
          - name: cinescope-data
            mountPath: /jupyter-data
      volumes:
      - name: cinescope-data
        persistentVolumeClaim:
          claimName: cinescope-data
