apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: flask-http
  template:
    metadata:
      labels:
        k8s-app: flask-http
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
      containers:
        - name: flask
          image: joelpolizzi/flask-dsc202:latest
          command: ["/bin/sh", "-c"]
          args: 
            - apt-get update && 
              apt-get install procps -y &&
              pip install psycopg2-binary pandas openai redis && 
              cd /jupyter-data/cinescope/jupyter-code/ && sh watchdog.sh
              #python app.py
              #sh /jupyter-data/cinescope/watchdog.sh
          resources:
            requests:
              memory: "32Gi"
              cpu: "25"
            limits:
              memory: "64Gi"
              cpu: "50"
          volumeMounts:
          - name: jupyter-data
            mountPath: /jupyter-data
      volumes:
      - name: jupyter-data
        persistentVolumeClaim:
          claimName: jupyter-data
