apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-pull
spec:
  replicas: 4
  selector:
    matchLabels:
      app: data-pull
  template:
    metadata:
      labels:
        app: data-pull
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
      containers:
        - name: data-pull
          image: ubuntu:22.04
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && \
              apt-get install vim python3 python3-venv python3-pip -y && \
              pip install requests && \
              while true; do
                ls -al /
                sleep 60
              done
          volumeMounts:
            - mountPath: /postgres-data
              name: data-pull
            - mountPath: /jupyter-data
              name: jupyter-data
      volumes:
        - name: data-pull
          persistentVolumeClaim:
            claimName: distributed-data
        - name: jupyter-data
          persistentVolumeClaim:
            claimName: jupyter-data
