apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
      containers:
        - name: neo4j
          image: neo4j:latest
          command: ["/bin/sh", "-c"]
          args:
            - neo4j start && sleep infinity
          resources:
            requests:
              cpu: "16"
              memory: "16Gi"
            limits:
              cpu: "20"
              memory: "32Gi"
          env:
            - name: NEO4j_AUTH
              value: "none"
            - name: NEO4J_dbms_memory_pagecache_size
              value: "8G"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "8G"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "16G"
            - name: NEO4J_server_bolt_listen__address
              value: "0.0.0.0:7687"
            - name: NEO4J_server_bolt_advertised__address
              value: "0.0.0.0:7687"
            - name: NEO4J_server_http_listen__address
              value: "0.0.0.0:7474"
            - name: NEO4J_server_http_advertised__address
              value: "0.0.0.0:7474"
            - name: NEO4J_server_https_enabled
              value: "false"
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-conf
              mountPath: /var/lib/neo4j/conf
            - name: cinescope-data
              mountPath: /cinescope-data
      volumes:
        - name: cinescope-data
          persistentVolumeClaim:
            claimName: cinescope-data
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data
        - name: neo4j-conf
          configMap:
            name: neo4j-conf
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
  type: ClusterIP
